import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
option_as_alt = "Both"

[window.dimensions]
columns = 140
lines = 36

[cursor]
style = "underline"

[font]
size = 13.0
normal.family = "JetBrainsMono Nerd Font"
