export PATH=/opt/homebrew/bin:$HOME/.cargo/bin:/opt/flutter/bin:$HOME/Library/Android/sdk/platform-tools:$HOME/go/bin:$HOME/.yarn/bin:/opt/ziglang:/opt/zls:$PATH

source ~/.zsh/completion.zsh

##############
# EXTENSIONS #
##############
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

###########
# HISTORY #
###########
HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

# Immediately append to history file:
setopt INC_APPEND_HISTORY

# Record timestamp in history:
setopt EXTENDED_HISTORY

# Expire duplicate entries first when trimming history:
setopt HIST_EXPIRE_DUPS_FIRST

# Don't record an entry that was just recorded again:
setopt HIST_IGNORE_DUPS

# Delete old recorded entry if new entry is a duplicate:
setopt HIST_IGNORE_ALL_DUPS

# Do not display a line previously found:
setopt HIST_FIND_NO_DUPS

# Don't write duplicate entries in the history file:
setopt HIST_SAVE_NO_DUPS

# Share history between all sessions:
setopt SHARE_HISTORY

# Execute commands using history (e.g.: using !$) immediatel:
unsetopt HIST_VERIFY


#####################
# CONFIGURE EDITORS #
#####################
export EDITOR="nvim"
export VISUAL="nvim"

###########
# ALIASES #
###########
alias ls='eza -lh --group-directories-first --icons'
alias lsa='ls -a'
alias lt='ls --tree --level=2 --git'
alias lta='lt -a'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"

alias vim="nvim"

###############
# SETUP TOOLS #
###############

# Theme for batcat
export BAT_THEME="catppuccin-frappe"

# Init starship
eval "$(starship init zsh)"

# Opam configuration
[[ ! -r ~/.opam/opam-init/init.zsh ]] || source ~/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# zellij
eval "$(zellij setup --generate-auto-start zsh)"

# atuin
eval "$(atuin init zsh)"

# bun completions
[ -s "/Users/vidd/.bun/_bun" ] && source "/Users/vidd/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# postgres
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
